---
title: "Group E 常態假設的重要性"
output: rmdformats::readthedown
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
set.seed(5678)
```

## Regression Model
$$\mathbb{Y}=\mathbb{X}\beta+\epsilon$$
Under $H_0 : \beta_i=0$.
```{r}
N <- 20 #樣本數
b <- matrix(c(0,0), nrow=2) #Beta
data <- data.frame('Sepal.Length'=iris[1:N, 1]) #simple linear
X <- model.matrix(~Sepal.Length, data=data)
B <- 3000 #重複次數
f <- rep(NA, B)
t <- 0
for (i in 1:B){
  error <- rnorm(n, 0, 1)  #n=20
  y <- X%*%b + error
  fit <- lm(y~X)
  anova <- anova(fit)
  f[i] <- anova$`F value`[1]
  if (anova$`Pr(>F)`[1]<=0.05) t <- t+1
}
```

```{r fig.width=6, fig.height=4}
levels <- data.frame('sample'=c(rep("A", 5), rep("B", 5), rep("C", 5), rep("D", 5)))
X1 <- model.matrix(~sample, data=levels)

B <- 3000 #重複次數
f <- rep(NA, B)
t <- 0
tau <- rep(0, N)
mu <- rep(3, N)
for (i in 1:B){
  error <- rnorm(N, 0, 1)  #n=20
  obs <- mu + tau + error
  fit <- lm(obs~X1)
  anova <- anova(fit)
  f[i] <- anova$`F value`[1]
  residual[i] <- mean(fit$residuals)
  if (anova$`Pr(>F)`[1]<=0.05) t <- t+1
}

par(bg="#fcfcfc")
plot(density(f), xlim=c(0,8), ylim=c(0,1), main="N(0, 1)", xlab="n")
curve(df(x, anova$Df[1], anova$Df[2]), col=2, add=T)
legend("topright", c("simulation F", "real F"), col=c(1,2), lty=1)
t/B # type I error
```

## **Confidence Interval for Type I Error**
```{r}
ci_upper <- 0.05+1.96*sqrt(0.05*0.05/B)
ci_lower <- 0.05-1.96*sqrt(0.05*0.05/B)
ci_upper ; ci_lower
```


# **Poisson Distribution**
```{r warning=FALSE}
set.seed(5678)
N <- c(30, 60, 120) #樣本數
lambda <- c(0.001, 0.003, 0.005, 0.01, 0.05, 0.1, 0.5)
D <- expand.grid(N, lambda)
colnames(D) <- c('N','lambda')
D <- cbind(D, 'type_I_error'=rep(NA, dim(D)[1]))

B <- 5000 #重複次數
b <- matrix(c(0,0), nrow=2)
#skewness <- lambda^(-0.5)

for (i in 1:dim(D)[1]) {
  data <- data.frame('Sepal.Length'=iris[1:D$N[i], 1]) #simple linear
  X1 <- model.matrix(~Sepal.Length, data=data)
  
  f <- rep(NA, B)
  t <- 0
  tau <- rep(0, D$N[i])
  mu <- rep(3, D$N[i])
  for (j in 1:B) {
    error <- rpois(D$N[i], D$lambda[i])-D$lambda[i]
    obs <- mu + tau + error
    fit <- lm(obs~X1)
    anova <- anova(fit)
    f[j] <- anova$`F value`[1]
    if (!is.nan(anova$`F value`[1])){
      if (anova$`Pr(>F)`[1] <= 0.05) {t <- t+1}
    }
  }
  D$type_I_error[i] <- round(t/B, 4)
}

D_s <- split(D, D$N)
plot(D_s$`30`$lambda, D_s$`30`$type_I_error, main='', type='b', ylab='p-value', ylim=c(0,0.06), xlab='lambda')
lines(D_s$`60`$lambda, D_s$`60`$type_I_error, type='b', col='blue', axes=F, ylab='', xlab='')
lines(D_s$`120`$lambda, D_s$`120`$type_I_error, type='b', col='green3', axes=F, ylab='', xlab='')
abline(h=0.05, col="red", lwd=2)
legend("bottomright", c('n=30','n=50','n=100'), col=c(1,'blue','green3'), lty=1)
```




# **Binomial Distribution**
skewness <- (1-p)*p/sqrt(n*p*(1-p))
```{r warning=FALSE}
set.seed(5678)
N <- 20 #樣本數
n <- c(1, 5, 10, 30)
p <- c(0.005, 0.01, 0.05, 0.1, 0.3)
D <- expand.grid(N, n, p)
colnames(D) <- c('N','n','p')
D <- cbind(D, 'type_I_error'=rep(NA, dim(D)[1]))

B <- 3000 #重複次數
for (i in 1:dim(D)[1]) {
  levels <- data.frame('sample'=c(rep("A",D$N[i]/4), rep("B",D$N[i]/4), rep("C",D$N[i]/4), rep("D",D$N[i]/4)))
  X1 <- model.matrix(~sample, data=levels)
  
  f <- rep(NA, B)
  t <- 0
  tau <- rep(0, D$N[i])
  mu <- rep(3, D$N[i])
  for (j in 1:B) {
    error <- rbinom(D$N[i], D$n[i], D$p[i]) - D$n[i]*D$p[i]
    obs <- mu + tau + error
    fit <- lm(obs~X)
    anova <- anova(fit)
    f[j] <- anova$`F value`[1]
    if (!is.nan(anova$`F value`[1])){
      if (anova$`Pr(>F)`[1] <= 0.05) {t <- t+1}
    }
  }
  D$type_I_error[i] <- round(t/B, 4)
}

D_s <- split(D, D$n)
plot(D_s$`1`$p, D_s$`1`$type_I_error, main='', type='b', ylab='p-value', ylim=c(0,0.06), xlab='p')
lines(D_s$`5`$p, D_s$`5`$type_I_error, type='b', col='blue', axes=F, ylab='', xlab='')
lines(D_s$`10`$p, D_s$`10`$type_I_error, type='b', col='green3', axes=F, ylab='', xlab='')
lines(D_s$`30`$p, D_s$`30`$type_I_error, type='b', col='orange', axes=F, ylab='', xlab='')
abline(h=0.05, col="red")
legend("bottomright", c('n=1','n=5','n=10','n=30'), col=c(1,'blue','green3','orange'), lty=1)
```

# **t Distribution**
```{r warning=FALSE}
set.seed(5678)
N <- c(8, 12, 16, 20) #樣本數
D <- data.frame('N'=rep(N,N-1), 'df'=sequence(N-1))
D <- cbind(D, 'type_I_error'=rep(NA, dim(D)[1]))

B <- 5000 #重複次數
for (i in 1:dim(D)[1]) {
  levels <- data.frame('sample'=c(rep("A",D$N[i]/4), rep("B",D$N[i]/4), rep("C",D$N[i]/4), rep("D",D$N[i]/4)))
  X1 <- model.matrix(~sample, data=levels)
  
  f <- rep(NA, B)
  t <- 0
  tau <- rep(0, D$N[i])
  mu <- rep(3, D$N[i])
  for (j in 1:B) {
    error <- rt(D$N[i], df=D$df[i])
    obs <- mu + tau + error
    fit <- lm(obs~X1)
    anova <- anova(fit)
    f[j] <- anova$`F value`[1]
    if (!is.nan(anova$`F value`[1])){
      if (anova$`Pr(>F)`[1] <= 0.05) {t <- t+1}
    }
  }
  D$type_I_error[i] <- round(t/B, 4)
}
```


```{r fig.width=10, fig.height=5, warning=FALSE, echo=FALSE}
ci_upper <- 0.05+1.96*sqrt(0.05*0.05/B)
ci_lower <- 0.05-1.96*sqrt(0.05*0.05/B)

stat <- rep(NA, length(N))
for (i in 1:length(N)) {
  a <- D$type_I_error[which(D$N==N[i])]
  stat[i] <- mean(ifelse((a < ci_upper) & (a > ci_lower),1 ,0))
}

D_s <- split(D, D$N)
plot(D_s$`20`$df, D_s$`20`$type_I_error, main='', type='b', ylab='p-value', ylim=c(0,0.06), xlab='df')
lines(D_s$`16`$df, D_s$`16`$type_I_error, type='b', col='green3', axes=F, ylab='', xlab='')
lines(D_s$`12`$df, D_s$`12`$type_I_error, type='b', col='orange', axes=F, ylab='', xlab='')
lines(D_s$`8`$df, D_s$`8`$type_I_error, type='b', col='blue', axes=F, ylab='', xlab='')

abline(h=0.05, col="red",lwd=2)
#abline(h=0.05, col=alpha("red", 0.2), lwd=13)
legend("bottomright", paste0('N=',N[1:4]), col=c('blue','orange','green3',1), lty=1.5)
```




```{r}
dd <- data.frame(a = gl(3,4), b = gl(4,1,12)) # balanced 2-way
options("contrasts") # typically 'treatment' (for unordered factors)
model.matrix(~ a + b, dd)
model.matrix(~ a + b, dd, contrasts = list(a = "contr.sum"))
model.matrix(~ a + b, dd, contrasts = list(a = "contr.sum", b = contr.poly))
```



